### PR TITLE
Bias toolbox

### PR DESCRIPTION
**Pull request by es-dell**
## Description

Compute bias in dataset

## Motivation and Context

Allow users to explore if there are any bias in the datasets

## Type of Change

feat: A new feature

## How to Test

[Provide clear instructions on how to test and verify the changes introduced by this pull request, including any specific unit tests you have created to demonstrate your changes.]

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [x]  I have added or updated the necessary documentation (README, API docs, etc.).
- [x]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [ ]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Comment by timlrx** [comment]
This contains both the bias toolbox and shap toolbox changes. It would be helpful if you could add more description to the pull request. Additional context, docs, screenshots would be great!

Without looking through the code, it's hard to understand what benefits these new tests bring compared to the existing fairness / shap test and why the changes are added as a new stock plugin then perhaps modified versions of the existing one.

**Comment by es-dell** [comment]
image

**Comment by kimeetok** [comment]
thanks @es-dell and team for this PR! 

Would you also be able to supplement the widget with additional elaboration on what the scores for 'statistic' and 'p-value' would mean for each metric? It should be written in a way that it can be understood by readers that might not be familiar with the algos. 

It would be great if you could also subsequently suggest actionable steps they can take according to the results, like the 'Recommendations' section from our exisiting partial dependence plot [here](https://github.com/aiverify-foundation/aiverify/blob/main/stock-plugins/aiverify.stock.partial-dependence-plot/README.md)

You can refer to [this](https://github.com/aiverify-foundation/aiverify/tree/main/stock-plugins/aiverify.stock.robustness-toolbox#readme) for a good example of how documentation for this plugin can be done :)

Please also remove Local SHAP from this PR so that we can manage that in #283 independently.

While we are in the midst of reviewing this PR, will get back to you soonest :)

**Comment by imda-benedictlee** [comment]
Hi @es-dell, I was able to get the bias toolbox setup as seen below:

bias-toolbox

Would like to check the following:
- Is this plugin offered as a stock plugin or as a standalone plugin?
- What is the sample data and model used to test Bias ToolBox Plugin?

Lastly, I see that the dist for "aiverify.stock.bias-toolbox" is not generated in the folder. Can you generate it and push it to the branch? Instructions can be found here: https://aiverify-foundation.github.io/aiverify-developer-tools/guided_example/deploy_your_plugin/. 

Please ensure that you have installed the AI Verify Developer Tools before deploying the plugin. The link to the AI Verify Developer Tools is here: https://github.com/aiverify-foundation/aiverify-developer-tools and the instructions to install can be found here: https://aiverify-foundation.github.io/aiverify-developer-tools/getting_started/install_aiverify_dev_tools/

Do reach out to me if you require assistance on this.

**Comment by es-dell** [comment]
- stock plugin
- testing was done using the standard data and model provided in the image

Is it possible to generate the dist on your end? We have removed the VM from our system, will have to reinstall

**Comment by imda-benedictlee** [comment]
Hi @es-dell, noted on the comments provided. Will upload the dist on our end.

**Comment by es-dell** [comment]
dist uploaded as requested

**Comment by imda-benedictlee** [comment]
Hi @es-dell, i was able to generate the bias toolbox in the report on my end as seen below:

image

Can I check if the Shap Toolbox has been removed from this PR? I still see it as part of the changes in the PR itself.

**Comment by imda-benedictlee** [comment]
Hi @es-dell, can I check if you have done the unit tests for the plugin?

**Comment by es-dell** [comment]
> Hi @es-dell, i was able to generate the bias toolbox in the report on my end as seen below:
> 
> image
> 
> Can I check if the Shap Toolbox Dist and Folder Changes has been removed from this PR? I still see it as part of the changes in the PR itself.

shap toolbox is part of imda original toolkit. pls provide list of files to remove

**Comment by es-dell** [comment]
> Hi @es-dell, can I check if you have done the unit tests for the plugin?

pls provide unit tests if to be done on our end

**Review by HanFai-IMDA — APPROVED** [review]

**Review by imda-benedictlee — APPROVED** [review]
Approved

**Comment by imda-benedictlee** [comment]
Bias ToolBox Report: 
[document.pdf](https://github.com/user-attachments/files/17073721/document.pdf)

**Pull request merged**
