### PR TITLE
Match plugins output to testresult schema

### PR DESCRIPTION
**Pull request by iamksuresh**
## Description

Updating the Plugin's output file (result.json) to match the common/testResult.schema.json file. 

## Type of Change

 feat: A new feature

## How to Test

Execute the below commands to run unit tests for any plugin - (say - robustness_toolbox )
```
cd aiverify/stock-plugins/aiverify.stock.robustness-toolbox/algorithms/robustness_toolbox/
python -m aiverify_robustness_toolbox --data_path ../../../user_defined_files/data/sample_bc_pipeline_credit_data.sav --model_path ../../../user_defined_files/pipeline/bc_tabular_credit --ground_truth_path ../../../user_defined_files/data/sample_bc_pipeline_credit_ytest_data.sav  --ground_truth default --model_type CLASSIFICATION  --annotated_ground_truth_path ../../../user_defined_files/data/pickle_pandas_fashion_mnist_annotated_labels_10.sav --file_name_label file_name --run_pipeline

```
This will create a output/results.json file. Validate it with common/testResult.schema.json file

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [x]  I have added or updated the necessary documentation (README, API docs, etc.).
- [x]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [x]  I have rebased my branch onto the latest commit of the main branch.
- [x]  I have squashed or reorganized my commits into logical units.
- [x]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Comment by iamksuresh** [comment]
@imda-peckyoke / @timlrx  : I have removed testDataset, mode from required fields. 
Ref here - https://github.com/aiverify-foundation/aiverify/pull/333/files#diff-8c157164acf1660e23c263e679426de1917ce0c5aea995bd1adf17071500dce7R91

If these are required fields, then what should be the value of those 2 attributes ?
Note -  Keeping it required fields fails schema validation.

**Comment by timlrx** [comment]
## Change Log

- Added a new `ITestResult` model in the core aiverify_test_engine and a `validate_test_result_schema` util function to validate against the testoutput schema. I have create a copy of the schema in `aiverify_test_engine` - we can see how to reduce duplicate in the future.
- Updated all `_generate_output_file` method in the stock plugins to use the pydantic model with additional validation with `validate_test_result_schema`.
- Updated all readme, including adding a reference to the main readme on the alpha library and plugins.
- Made the stock plugin kebab case instead of snake case to be consistent for publishing to pypi. 
- Build a copy of the test-engine and all the stock plugins for publishing.

## Tests
Here's the test results with all the schema changes made to the plugins - [all_test_3.10.log](https://github.com/user-attachments/files/17179614/all_test_3.10.log)

And here's a full integration test which installs `aiverify-test-engine`, before proceeding to installing the wheels of each stock plugin and running the e2e test - [install_and_test.log](https://github.com/user-attachments/files/17179616/install_and_test.log)

To replicate, run the following script:
```sh
pip install ../aiverify-test-engine/dist/*.whl
pip install pytest
export BREW_PREFIX=$(brew --prefix)
export MAGICK_HOME="$BREW_PREFIX/opt/imagemagick@6"

for dir in aiverify*/algorithms/*; do
    if [ -d "$dir" ]; then
        if [ -f "$dir/pyproject.toml" ]; then
            echo "Running pip install in $dir"
            (cd "$dir" && pip install dist/*.whl)
            echo "Running pytest in $dir" | tee -a install_and_test.log
            (cd "$dir" && python -m pytest tests/e2e) | tee -a install_and_test.log
        fi
    fi
done
```

Run `pip list` to verify that all the versions and package names are set correctly:
Screenshot 2024-09-29 at 10 44 52 PM

**Review by imda-peckyoke — CHANGES_REQUESTED** [review]
Ensure that the gid specified in the algo.meta.json is the same as that specified in plugin.meta.json.
For example, currently for `aiverify.stock.image_corruption_toolbox`, the gid specified in the algo.meta.json is `aiverify.algorithms.blur_corruptions`

**Comment by timlrx** [comment]
> Ensure that the gid specified in the algo.meta.json is the same as that specified in plugin.meta.json. For example, currently for `aiverify.stock.image_corruption_toolbox`, the gid specified in the algo.meta.json is `aiverify.algorithms.blur_corruptions`

Fixed the gid to use the parent gid reference i.e. for blur_corruption, gid would be `aiverify.stock.image_corruption_toolbox`. Also deleted the redundant `plugin.meta.json` file in some folders. Built a new distributable for the algorithms that has their gid changed.

Verified that all test cases pass: 
[install_and_test.log](https://github.com/user-attachments/files/17184151/install_and_test.log)

**Review by imda-peckyoke — APPROVED** [review]
approve

**Pull request merged**
