### PR TITLE
Local shap toolbox

### PR DESCRIPTION
**Pull request by es-dell**
## Description

Local explainability toolbox

## Motivation and Context

Allow user to perform local explainabilty test

## Type of Change

feat: A new feature 

## How to Test

[Provide clear instructions on how to test and verify the changes introduced by this pull request, including any specific unit tests you have created to demonstrate your changes.]

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [x]  I have tested the changes locally and verified that they work as expected.
- [x]  I have added or updated the necessary documentation (README, API docs, etc.).
- [x]  I have added appropriate unit tests or functional tests for the changes made.
- [x]  I have followed the project's coding conventions and style guidelines.
- [ ]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have added any necessary dependencies or packages to the project's build configuration.
- [x]  I have performed a self-review of my own code.
- [x]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilises.

## Screenshots (if applicable)

[If the changes involve visual modifications, include screenshots or GIFs that demonstrate the changes.]

## Additional Notes

[Add any additional information or context that might be relevant to reviewers.]

<details>
  <summary>Developer Certificate of Origin</summary>

 ```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
 ```
</details>

### CODE REVIEW

**Comment by es-dell** [comment]
image

**Comment by imda-benedictlee** [comment]
Hi @es-dell, I was able to get the local shap working on my setup as seen below:

local-shap-toolbox

Would like to check the following:
- Is this plugin offered as a stock plugin or as part of Shap Toolbox?
- What is the sample data and model used to test Local Shap?

**Comment by es-dell** [comment]
- Understand that this local shap plugin was a request by AIVerify, so it remains up to AIVerify on how to offer this plugin. Seems like it should be part of the shap toolbox
- testing was done using the standard data and model provided in the image

**Comment by imda-benedictlee** [comment]
Hi @es-dell, thanks for the heads up. Will test the plugin and get back to you on it.

**Comment by imda-benedictlee** [comment]
Hi @es-dell, I am facing some invalid plugin schema for Shap Toolbox. Can you help take a look on your end? It was unable to load automatically as a stock plugin as seen here:

image

There is also an invalid schema in the logs itself:
`Unable to read JSON from file /home/benedict/Documents/GitHub/aiverify/setup-aiverify/aiverify-dev/aiverify/ai-verify-portal/plugins/aiverify.stock.shap-toolbox/plugin.meta.json
Error reading plugin: Invalid plugin schema
`

Please advise.

**Comment by imda-benedictlee** [comment]
Hi @es-dell, can I check if you have done the unit tests for the plugin?

**Comment by es-dell** [comment]
> Hi @es-dell, I am facing some invalid plugin schema for Shap Toolbox. Can you help take a look on your end? It was unable to load automatically as a stock plugin as seen here:
> 
> image
> 
> There is also an invalid schema in the logs itself: `Unable to read JSON from file /home/benedict/Documents/GitHub/aiverify/setup-aiverify/aiverify-dev/aiverify/ai-verify-portal/plugins/aiverify.stock.shap-toolbox/plugin.meta.json Error reading plugin: Invalid plugin schema `
> 
> Please advise.

image

no issues for me, pls search with correct keyword

**Comment by es-dell** [comment]
> Hi @es-dell, can I check if you have done the unit tests for the plugin?

pls provide unit tests if to be done on our end

**Comment by imda-benedictlee** [comment]
Hi @es-dell, I retried the above again and am still encountering the same issue:
image

image

Please advise. Also, once this issue is resolved, can the fix be pushed to the bias toolbox PR as well? The issue seems to be occurring in bias toolbox PR due to the addition previously before the split into two separate PRs.

**Comment by es-dell** [comment]
I am not able to replicate the error. Did you install the newest plugin.zip? shap toolbox is provided by AIVerify, so no reason why you are unable to locate it in the plugin manager

**Comment by imda-benedictlee** [comment]
Hi @es-dell, can you rename this plugin root folder to local shap toolbox?

**Comment by es-dell** [comment]
Unsure of what you mean. Based on previous discussions with AIVerify, the local_shap_toolbox was to be added as an algorithm within the provided stock plugin aiverify.stock.shap-toolbox/algorithms
image

**Comment by imda-benedictlee** [comment]
Hi @es-dell, apologies for the long back and forth. We have decided to merge the local shap as is. Before we proceed, possible if you could help me resolve the conflict on README.md?

**Review by imda-benedictlee — DISMISSED** [review]
Approved

**Review by HanFai-IMDA — DISMISSED** [review]
Ok

**Review by imda-benedictlee — APPROVED** [review]
Approved

**Review by HanFai-IMDA — APPROVED** [review]
Ok

**Pull request merged**
